### PR TITLE
DE-Translation

### PR DESCRIPTION
**Pull request by raphipod**
Progress: 266/622 strings translated;

next PR will be when every string is translated to minimize the effort for the project owner.

### CODE REVIEW

**Comment by xraymemory** [comment]
Hey there - just add a new commit to these PR when the strings are all added and we can merge it in one fell swoop !

**Comment by raphipod** [comment]
Phew. I'm finished. @xraymemory The translation is now ready to merge into your main branch!

**Comment by xraymemory** [comment]
Thanks so much @raphipod! The actual work of getting the translation into the game is a little trickier than just running the Python script (that just generated the form files) so if you want some info on that, let me know! Either way so great to have this :)

**Comment by raphipod** [comment]
Yeah, it would be great to get some insight on the actual whole and what the python script is actually doing. I mean, I kind of understand it, but not entirely. @xraymemory What would you think about a Discord where we can exchange? That would be great!

**Comment by xraymemory** [comment]
The Python script essentially replaces strings from one language to another in the decompiled source files. However, to actually get the translated strings into the game one has to manually edit the .exe using  [VBReFormer](https://qiil.io/VBReFormer.aspx) and change the captions there. The source files are there so when you open them up in Visual Studio 6, you can see the forms and have a sort of map to what you are changing in the executable. Unfortunately, I've thus been far been unable to recompile the translated source hence the direct patching of the binary. It's time consuming and the VBReFormer software itself is unstable and does strange things to the executable so definitely looking for a better method.

I'm not the biggest discord user but if you think it'll be helpful then go for it! I'm working on a write-up right now detailing the process and outlining future goals

**Pull request merged**
